name: meetup_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # date format
  intl: ^0.18.0

  # calendar widget
  table_calendar: ^3.0.0

  # epxandable widgets
  expandable: ^5.0.1

  # state management
  flutter_bloc: ^7.0.0

  # comparing dart objects
  equatable: ^2.0.0

  # service locator
  get_it: ^6.0.0

  # data error handling
  dio: ^5.3.3

  # api interface
  retrofit: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/samples/
    - assets/images/default/
    - assets/images/samples/team_photo.png
